name: CI Quality Checks

on:
  push:
    branches: [ "main", "master", "chore/pytest" ]
  pull_request:
    branches: [ "main", "master", "chore/pytest" ]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        export PIP_REQUIRE_HASHES=true
        export PIP_ONLY_BINARY=:all:
        printf "https://pythonhosted.org#sha256:13ab279d520146a3401d56af946699ca40de062082cfe1d721c5afe301941971 --hash=sha256:13ab279d520146a3401d56af946699ca40de062082cfe1d721c5afe301941971\n" > pip-upgrade.txt
        python -m pip install -r pip-upgrade.txt
        rm pip-upgrade.txt
        pip install --no-deps -e .
        pip install --require-hashes --only-binary :all: --no-deps -r requirements.txt

    - name: Execute Automated Security Tests
      env:
        secret_key: ${{ secrets.TEST_SECRET_KEY }}
      run: |
        pytest --maxfail=1 --disable-warnings

  quality-control:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        export PIP_REQUIRE_HASHES=true
        export PIP_ONLY_BINARY=:all:
        printf "https://pythonhosted.org#sha256:13ab279d520146a3401d56af946699ca40de062082cfe1d721c5afe301941971 --hash=sha256:13ab279d520146a3401d56af946699ca40de062082cfe1d721c5afe301941971\n" > pip-upgrade.txt
        python -m pip install -r pip-upgrade.txt
        rm pip-upgrade.txt
        python -m pip install ruff bandit toml

    - name: Run Ruff Formatter (Black style)
      run: ruff format --check .

    - name: Run Ruff Linter
      run: ruff check .

    - name: Run Bandit Security Scanner
      run: python -m bandit -r . -c pyproject.toml
