name: Deploy Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv (Astral)
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install mkdocs-material

        run: | 
          apt install python3-xyz
          uv pip install mkdocs-material --system --only-binary :all:

      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force


