name: Automated Testing & Audit Logs

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-python-version: '3.11'
    
    - name: Mount Local Code & Python Modules
      run: |
        unset PIP_REQUIRE_HASHES
        unset PIP_ONLY_BINARY
        python -m pip install --no-deps -e .


    - name: Install dependencies
      run: |
        export PIP_REQUIRE_HASHES=true
        export PIP_ONLY_BINARY=:all:
        python -m pip install --no-deps -r ci-tools.txt
        python -m pip install --no-deps -r requirements.txt

    - name: Run automated tests
      run: |
        pytest --junitxml=test-results/report.xml
      

    - name: Run Pytest & Generate MD Log
      run: |
        pytest --md-report --md-report-output pytest-report.md
      continue-on-error: true 


    - name: Post Report to PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          file_path: pytest-report.md
          comment_tag: pytest_results 

    - name: Archive Test Log Artifacts
      if: always() 
      uses: actions/upload-artifact@v4
      with:
        name: test-execution-logs-${{ github.run_number }}
        path: test-results/
        retention-days: 30
